# Generated by Django 5.1.5 on 2025-01-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0003_alter_destination_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
